spring.application.name=WithDayBack

# 기본 포트
server.port=${SERVER_PORT:10400}

# MyBatis
mybatis.mapper-locations=classpath:mappers/**/*.xml
mybatis.type-aliases-package=com.test.withdayback
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=NULL

# SQL 로그
logging.level.com.test.withdayback.mapper=debug

# 파일 업로드 용량 제한
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB